# Configure training, validation, and evaluation data
# NOTE: text_data is filled with tid, fid, fname (audio_fname), raw_text (raw_caption), text (smallcase_without_any_punc_marks), tokens (for text field)
data_conf:
    train_data: # training data
        dataset: ./data/exp_3
        audio_data: development_audio_logmels.hdf5
        text_data: development_text.csv
        text_embeds: sbert_embeds.pkl
        text_level: sentence

    val_data: # validation data
        dataset: ./data/exp_3
        audio_data: validation_audio_logmels.hdf5
        text_data: validation_text.csv
        text_embeds: sbert_embeds.pkl
        text_level: sentence

    eval_data: # evaluation data
        dataset: ./data/exp_3
        audio_data: evaluation_audio_logmels.hdf5
        text_data: evaluation_text.csv
        text_embeds: sbert_embeds.pkl
        text_level: sentence

# Configure hyper-parameters
param_conf:
    num_epoch: 100
    batch_size: 32
    model: DualEncoderModel
    criterion: infonce_loss
    optimizer: AdamOptimizer
    lr_scheduler: ReduceLROnPlateau
    early_stopper: EarlyStopping

# Model definitions
DualEncoderModel:
    name: DualEncoderModel
    out_norm: L2
    audio_enc:
        name: CNN14Encoder
        init: prior
        weight: "./pretrained_models_weights/CNN14_300.pth"
        fc_dropout: 0.111650527250578
        conv_dropout: 0.13353659198165377
        fc_units: 1457
        conv_fine_tune_from: 4
        out_dim: 300

    text_enc:
        name: SentBERTBaseEncoder
        fc_units: 901
        init: prior
        out_dim: 300

# Criteria
criteria:
    infonce_loss:
        name: LogSoftmaxLoss
        args:
            temperature: 0.08525484428365834
            dist: dot_product # dot_product, cosine_similarity

# Optimizer definitions
AdamOptimizer:
    name: Adam
    args:
        lr: 0.0008146651275669621
        weight_decay: 0.0

# Learning rate scheduler definitions
ReduceLROnPlateau:
    name: ReduceLROnPlateau
    args:
        mode: min
        factor: 0.1
        patience: 5
        threshold: 0.005
        threshold_mode: abs
        min_lr: 0.000001
        verbose: true

# Early stopping
EarlyStopping:
    name: EarlyStopping
    args:
        patience: 10
        min_delta: 0.001

# Weights & Biases Configuration
wandb_conf:
    project: "best-param-runs"
